-d C:\Users\melii\OneDrive\Belgeler\fpga_project_7\impl\gwsynthesis\fpga_project_7.vg
-p GW1NZ-1-QFN48-6
-pn GW1NZ-LV1QN48C6/I5
-cst C:\Users\melii\OneDrive\Belgeler\fpga_project_7\src\fpga_project_7.cst
-cfg C:\Users\melii\OneDrive\Belgeler\fpga_project_7\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-route_maxfan 10
